const { execFileSync } = require('child_process')
const fs = require('fs')
const path = require('path')

// Builds a distribution-ready THIRD-PARTY-NOTICES.txt: for every production
// dependency it embeds the package's actual license text (not a local path),
// so the file can ship alongside the packaged app. Re-run after dependency
// changes: `node scripts/generate-notices.js`.

const root = path.resolve(__dirname, '..')
const outFile = path.join(root, 'THIRD-PARTY-NOTICES.txt')

function readLicenses() {
  const raw = execFileSync(
    process.platform === 'win32' ? 'npx.cmd' : 'npx',
    ['--yes', 'license-checker', '--production', '--json'],
    { cwd: root, maxBuffer: 64 * 1024 * 1024, encoding: 'utf8', shell: true }
  )
  return JSON.parse(raw)
}

function licenseText(info) {
  if (info.licenseFile && fs.existsSync(info.licenseFile)) {
    try {
      return fs.readFileSync(info.licenseFile, 'utf8').trim()
    } catch {
      /* fall through */
    }
  }
  return `(No license file bundled in this package. Declared license: ${info.licenses}.)`
}

function main() {
  const pkgs = readLicenses()
  const selfName = require(path.join(root, 'package.json')).name

  const names = Object.keys(pkgs)
    .filter((n) => !n.startsWith(`${selfName}@`))
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))

  const sep = '='.repeat(78)
  const parts = [
    'THIRD-PARTY SOFTWARE NOTICES',
    '',
    'This application includes the open-source components listed below. Each is',
    'distributed under its own license; the full text of each license follows its',
    'entry. This file is generated by scripts/generate-notices.js.',
    '',
    `Generated: ${new Date().toISOString().slice(0, 10)}`,
    `Components: ${names.length}`,
    '',
    'NOTE: The native image component "sharp" (libvips) is covered in part by the',
    'LGPL-3.0-or-later license (text included below). It is dynamically linked and',
    'may be replaced. Electron and its bundled Chromium/Node notices are shipped',
    'separately by electron-builder inside the packaged desktop app.',
    '',
  ]

  for (const name of names) {
    const info = pkgs[name]
    parts.push(sep)
    parts.push(name)
    parts.push(`License: ${info.licenses}`)
    if (info.repository) parts.push(`Repository: ${info.repository}`)
    if (info.publisher) parts.push(`Publisher: ${info.publisher}`)
    parts.push('')
    parts.push(licenseText(info))
    parts.push('')
  }

  fs.writeFileSync(outFile, parts.join('\n'), 'utf8')
  console.log(`Wrote ${outFile} (${names.length} components).`)
}

main()
